name: Continuous Integration Laravel 6

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    services:
      mysql-service:
        image: mariadb:latest
        env:
          MYSQL_DATABASE: harubiru
          MYSQL_USER: harubiru
          MYSQL_PASSWORD: ${{ secrets.HARUBIRU_DB_PASSWORD }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.HARUBIRU_DB_PASSWORD }}
        ports:
          - 33306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    
    steps:
    - uses: actions/checkout@test
    - name: Verify MariaDB connection
      env:
        PORT: ${{ job.services.mariadb.ports[33306] }}
        run: |
          while ! mysqladmin ping -h"127.0.0.1" -P"$PORT" --silent; do
            sleep 1
          done
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.ci', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: mysql
        DB_DATABASE: harubiru
        DB_PORT: 33306
        DB_USER: root
        DB_PASSWORD: ${{ secrets.HARUBIRU_DB_PASSWORD }}
      run: vendor/bin/phpunit
    - name: Dump Autoload
      run: composer dump-autoload
    - name: Migrate and Seed DB
      run: php artisan migrate:fresh --seed
